[package]
name = "users"
version = "1.0.0"
authors = []

[addresses]
my_adr = "71be0e1248f94c261bce70c8202ad89d95ef7429837956eb48a0ef9f1c21e662"

[dev-addresses]
my_adr = "0xc6a12738a7cef2596294cc68be22aa945b003bc13606ac7f0e9627d57ffc3954"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
