[package]
name = "users"
version = "1.0.0"
authors = []

[addresses]
my_adr = "8503e977d16f320c0d89ce80428c678946db1f1d172945bdeb8a050dd9d3778f"

[dev-addresses]
my_adr = "0xc6a12738a7cef2596294cc68be22aa945b003bc13606ac7f0e9627d57ffc3954"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
